# Generated by Django 2.2.4 on 2019-09-01 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bills', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('building_name', models.CharField(max_length=50)),
                ('address', models.TextField(default='Provide Description')),
                ('square_footage', models.IntegerField()),
                ('electricity_provider', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('co2_current', models.FloatField()),
                ('co2_2024', models.FloatField()),
                ('co2_2030', models.FloatField()),
                ('aggregated_bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Bill')),
                ('applicable_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Use')),
            ],
        ),
    ]
