# Generated by Django 2.2.4 on 2019-09-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='applicable_options',
        ),
        migrations.AddField(
            model_name='building',
            name='applicable_options',
            field=models.ManyToManyField(to='survey.Option'),
        ),
    ]
