# Generated by Django 2.2.4 on 2019-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190901_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='aggregated_bills',
        ),
        migrations.AddField(
            model_name='building',
            name='aggregated_bills',
            field=models.ManyToManyField(to='survey.Bill'),
        ),
        migrations.RemoveField(
            model_name='building',
            name='uses',
        ),
        migrations.AddField(
            model_name='building',
            name='uses',
            field=models.ManyToManyField(to='survey.Use'),
        ),
    ]
